server:
  port: 8080

st:
  resource:
    template-path: C:\projects\st-report\src\main\resources\templates
    output-path: C:\projects\st-report\target
logging:
  level:
    root: trace

spring:
  application:
    name: st-report